const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = [
  './src/routes/client/index',
  './src/routes/address/index',
];

const doc = {
  info: {
    version: '0.1.0',
    title: 'TeamSoft - backend',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Client',
      description: 'Endpoints',
    },
    {
      name: 'Address',
      description: 'Endpoints',
    },
  ],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./src/server.ts');
});
